### ISSUE TITLE
t/reddit.t test fails (redirect issue? changed WWW-Shorten-Bitly API?)

### ISSUE THREAD

**Issue by eserte** [aggrolite/POE-Component-IRC-Plugin-WWW-Reddit-TIL#1]
My smoker systems start to report failures in the test suite:

```
Can't use an undefined value as a HASH reference at /home/cpansand/.cpan/build/2016092721/POE-Component-IRC-Plugin-WWW-Reddit-TIL-0.07-4/blib/lib/POE/Component/IRC/Plugin/WWW/Reddit/TIL.pm line 52.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 2.
t/reddit.t .............. 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 2 subtests passed 
```

(See also http://matrix.cpantesters.org/?dist=POE-Component-IRC-Plugin-WWW-Reddit-TIL;reports=1#sl=7,1 for an overview)

I think there are at least two issues involved here:
- The reddit URL now redirects from http to https. It seems that Mojo::UserAgent has to be told to actually do the redirects, e.g. by calling `$ua->max_redirects(7)` or so.
- WWW-Shorten-Bitly was completely revamped some weeks ago and it seems that even with the fix above it does not work anymore with version 2:

```
t/reddit.t .............. 1/? Can't login without at least a username and password at /opt/perl-5.24.0/lib/site_perl/5.24.0/WWW/Shorten/Simple.pm line 49.
```

**Comment by aggrolite** [comment]
thanks - using HTTPS links now, removed WWW::Shorten dependency.
