### ISSUE TITLE
https requests with Mojo::UserAgent require IO::Socket::SSL

### ISSUE THREAD

**Issue by Grinnz** [aggrolite/POE-Component-IRC-Plugin-WWW-Reddit-TIL#2]
To use Mojo::UserAgent to make HTTPS requests you should have a dependency on IO::Socket::SSL 1.94. https://metacpan.org/pod/Mojo::UserAgent#DESCRIPTION

**Comment by aggrolite** [comment]
Thanks for the heads up - pushed to CPAN
